builder = "DOCKERFILE"

[phases.build]
cmds = [
  # Install PHP dependencies
  "composer install --no-dev --optimize-autoloader",
  
  # Install Node & build assets
  "npm install",
  "npm run build"
]
